### ISSUE TITLE
Exception: pync is only supported on Mac OS X 10.8, or higher.

### ISSUE THREAD

**Issue by powerful-heart** [UFund-Me/Qbot#25]
'which' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "D:\WorkZoom\600001\Qbot\auto_monitor.py", line 25, in <module>
    import pync
  File "C:\Python38\lib\site-packages\pync\__init__.py", line 3, in <module>
    from .TerminalNotifier import Notifier, notify
  File "C:\Python38\lib\site-packages\pync\TerminalNotifier.py", line 137, in <module>
    Notifier = TerminalNotifier()
  File "C:\Python38\lib\site-packages\pync\TerminalNotifier.py", line 37, in __init__
    raise Exception("pync is only supported on Mac OS X 10.8, or higher.")
Exception: pync is only supported on Mac OS X 10.8, or higher.

windows下运行auto_monitor.py报错
![image](https://github.com/UFund-Me/Qbot/assets/42861905/1e688256-e6e1-474f-8ac0-e5834667410a)

**Comment by Charmve** [comment]
这是我没考虑到的，pync是mac上的一个桌面提示窗库，win系统下没有，可以注释掉使用到的代码。
