### ISSUE TITLE
SetuptoolsDeprecationWarning: Invalid dash-separated options

### ISSUE THREAD

**Issue by baiyutang** [UFund-Me/Qbot#57]
## ❓ Questions and Help

We sincerely suggest you to carefully read the [wiki](https://github.com/Charmve/Qbot/wiki) of our library. After that, if you still feel puzzled, please describe the question clearly under this issue.

```
Collecting wxPython (from -r requirements.txt (line 2))
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/aa/64/d749e767a8ce7bdc3d533334e03bb1106fc4e4803d16f931fada9007ee13/wxPython-4.2.1.tar.gz (73.7 MB)
  Preparing metadata (setup.py) ... done
Collecting pandas (from -r requirements.txt (line 3))
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/9e/0d/91a9fd2c202f2b1d97a38ab591890f86480ecbb596cbc56d035f6f23fdcc/pandas-2.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
Collecting matplotlib==3.2.2 (from -r requirements.txt (line 4))
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/9c/4b/06f4aa9bef6b5e4f177881b4dedd94faa6e7cb3d95dfaeaa8a1a8b541095/matplotlib-3.2.2.tar.gz (40.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      /root/anaconda3/envs/qbot/lib/python3.9/site-packages/setuptools/dist.py:755: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'index-url' will not be supported in future
              versions. Please use the underscore name 'index_url' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      /root/anaconda3/envs/qbot/lib/python3.9/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
      ERROR: Could not find a version that satisfies the requirement numpy>=1.11 (from versions: none)
      ERROR: No matching distribution found for numpy>=1.11
      Traceback (most recent call last):
        File "/root/anaconda3/envs/qbot/lib/python3.9/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/root/anaconda3/envs/qbot/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/root/anaconda3/envs/qbot/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpu794fwrj', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'numpy>=1.11']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-iwf6nksl/matplotlib_77c7c00d860e442e9e577d23d5cc2a67/setup.py", line 236, in <module>
          setup(
        File "/root/anaconda3/envs/qbot/lib/python3.9/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/root/anaconda3/envs/qbot/lib/python3.9/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/root/anaconda3/envs/qbot/lib/python3.9/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/root/anaconda3/envs/qbot/lib/python3.9/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/root/anaconda3/envs/qbot/lib/python3.9/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/root/anaconda3/envs/qbot/lib/python3.9/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
```

![image](https://github.com/UFund-Me/Qbot/assets/10782183/824d8287-3f99-45c5-b0d4-d7ec3349d03f)

look at requirest.txt

you shloud execute this :
```
pip install git+https://github.com/quantopian/pyfolio
```

**Comment by oendnsk675** [comment]
i've face this promblem today, and i try to install gcc on my ubuntu, and solved, u can try to install gcc before and make sure using C++11
