### ISSUE TITLE
请问是否支持部署在云服务器CentOS上面

### ISSUE THREAD

**Issue by ODomWang** [UFund-Me/Qbot#70]
`
[root@instance-6olzww4q Qbot]# python main.py
Traceback (most recent call last):
  File "/home/Qbot/main.py", line 12, in <module>
    frame = MainFrame(None, title="AI智能量化投研平台")
  File "/home/Qbot/gui/mainframe.py", line 110, in __init__
    homepage = WebPanel(self.m_notebook)
  File "/home/Qbot/gui/widgets/widget_web.py", line 11, in __init__
    self.browser = web.WebView.New(self)
NotImplementedError

`
部署报错NotImplementedError

**Comment by Charmve** [comment]
这个依赖了wxPython 可视化窗口的方式，可以去掉前端，也可以通过flask或react 写一个前端；跑后端服务应该是ok 的。

**Comment by jg0014** [comment]
> 这个依赖了wxPython 可视化窗口的方式，可以去掉前端，也可以通过flask或react 写一个前端；跑后端服务应该是ok 的。

您在开发的时候还是主要考虑windows平台的吗

**Comment by Charmve** [comment]
> > 这个依赖了wxPython 可视化窗口的方式，可以去掉前端，也可以通过flask或react 写一个前端；跑后端服务应该是ok 的。
> 
> 您在开发的时候还是主要考虑windows平台的吗

@jg0014 ubuntu\win\mac 都是支持的
