### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ximalayashanjiao** [UFund-Me/Qbot#75]
- Qbot version: 最新版
- Python version: conda 虚拟环境python3.9.18
- OS (`Windows`, `Linux`, `MacOS`): win10
- Commit number (optional, please provide it if you are using the dev version):

运行main.py文件后提示如下错误：
Traceback (most recent call last):
  File "C:\Users\MI\Documents\BaiduSyncdisk\Qbot\auto_monitor.py", line 126, in <module>
    if check("sh", 3300, 10000) or check("601318", 0, 49):
  File "C:\Users\MI\Documents\BaiduSyncdisk\Qbot\auto_monitor.py", line 108, in check
    df = ts.get_realtime_quotes(code)
  File "c:\Users\MI\anaconda3\envs\env_4\lib\site-packages\tushare\stock\trading.py", line 380, in get_realtime_quotes
    text = urlopen(request,timeout=10).read()
  File "c:\Users\MI\anaconda3\envs\env_4\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "c:\Users\MI\anaconda3\envs\env_4\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\Users\MI\anaconda3\envs\env_4\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\Users\MI\anaconda3\envs\env_4\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\Users\MI\anaconda3\envs\env_4\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\Users\MI\anaconda3\envs\env_4\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
![微信图片_20240227111458](https://github.com/UFund-Me/Qbot/assets/12340211/12d24a05-989a-4e6b-ba3d-542fc2599b40)

**Comment by ljhust** [comment]
一样的错误，无法访问tushare

**Comment by townlet** [comment]
一样的错误，请问解决了吗，我电脑网络连接的是手机个人热点
