### ISSUE TITLE
Windows Python3.9安装过程报错module 'configparser' has no attribute 'SafeConfigParser'

### ISSUE THREAD

**Issue by devin-wang-ni** [UFund-Me/Qbot#89]
Windows Python3.9安装过程报错AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? 请问怎么解决呢？

PS D:\Quant\Qbot-main> pip install -r requirements.txt
Collecting git+https://github.com/quantopian/pyfolio (from -r requirements.txt (line 5))
  Cloning https://github.com/quantopian/pyfolio to c:\users\wangl\appdata\local\temp\pip-req-build-5a2blp37
  Running command git clone --filter=blob:none --quiet https://github.com/quantopian/pyfolio 'C:\Users\wangl\AppData\Local\Temp\pip-req-build-5a2blp37'
  Resolved https://github.com/quantopian/pyfolio to commit 4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      C:\Users\wangl\AppData\Local\Temp\pip-req-build-5a2blp37\versioneer.py:468: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\wangl\AppData\Local\Temp\pip-req-build-5a2blp37\setup.py", line 67, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\wangl\AppData\Local\Temp\pip-req-build-5a2blp37\versioneer.py", line 1407, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\wangl\AppData\Local\Temp\pip-req-build-5a2blp37\versioneer.py", line 1341, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\wangl\AppData\Local\Temp\pip-req-build-5a2blp37\versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by xuxuzhaozhao** [comment]
一样的问题，而且装好后，也是依托答辩，不用安装了。

**Comment by SimbaLiu** [comment]
python版本太高了。https://blog.csdn.net/gitblog_07374/article/details/148707201，我也正在解决
