### ISSUE TITLE
No module named 'qbot.engine.config'

### ISSUE THREAD

**Issue by cctni** [UFund-Me/Qbot#90]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\home\Qbot\qbot\gui\panels\panel_sim_trade.py", line 447, in OnClickTrade
    self.trade_engine = TradeEngine(self.trader_opts, self.syslog)
  File "C:\Users\Administrator\Desktop\home\Qbot\qbot\engine\trade\trade_engine.py", line 25, in __init__
    self.TradeEngine = SimTradeEngine(self.trade_opts, syslog_obj=self.syslog)
  File "C:\Users\Administrator\Desktop\home\Qbot\qbot\engine\trade\trade_sim.py", line 105, in __init__
    from qbot.engine.config import BTC_SIM_ACCOUNT
ModuleNotFoundError: No module named 'qbot.engine.config'

**Comment by Charmve** [comment]
在代码主目录，执行python mian.py

**Comment by fxgxxhh** [comment]
> 在代码主目录，执行python mian.py
你好，我同样遇到了这个问题，在主目录执行python mian.py 后在qbot.engine下面依然没有出现config模块

![Image](https://github.com/user-attachments/assets/69785633-a5c3-4823-9b79-e824ea37f71e)

**Comment by YongcanZhou** [comment]
+1

**Comment by kuyoeku** [comment]
+2

**Comment by Aloento** [comment]
+3

**Comment by Charmve** [comment]
设置一下PYTHONPATH环境变量，如：
项目目录 ~/workspace/Qbot，就设置为
```bash
export PYTHONPATH=~/workspace/Qbot
```
然后，
```
cd ~/workspace/Qbot
python main.py 
#mac pythonw main.py
```
